import { schema, t } from '@colyseus/schema';
import type { SchemaType } from '@colyseus/schema';
import type {
  GameSnapshot,
  PlayerSnapshot,
  WeaponId,
  ChallengeSnapshot,
} from './index.js';

export const ChallengeState = schema(
  {
    kind: t.string<ChallengeSnapshot['kind']>().default('training'),
    status: t.string<ChallengeSnapshot['status']>().default('idle'),
    weapon: t.string<WeaponId>().default('rifle'),
    runId: t.uint32().default(0),
    elapsed: t.float32().default(0),
    remaining: t.float32().default(0),
    duration: t.float32().default(0),
    shots: t.uint32().default(0),
    hits: t.uint32().default(0),
    headshots: t.uint32().default(0),
    reactionMs: t.float32().default(0),
    checkpoint: t.uint8().default(0),
    targetIndex: t.int8().default(-1),
    targetTick: t.uint32().default(0),
  },
  'ChallengeState',
);

export const PlayerState = schema(
  {
    id: t.string().default(''),
    bot: t.boolean().default(false),
    ally: t.boolean().default(false),
    reserveAmmo: t.uint16().default(0),
    secondaryReserve: t.uint16().default(0),
    bloom: t.float32().default(0),
    supplyCooldown: t.float32().default(0),
    challenge: t.ref(ChallengeState),
    nickname: t.string().default(''),
    x: t.float32().default(0),
    y: t.float32().default(0),
    z: t.float32().default(0),
    vx: t.float32().default(0),
    vy: t.float32().default(0),
    vz: t.float32().default(0),
    yaw: t.float32().default(0),
    pitch: t.float32().default(0),
    grounded: t.boolean().default(false),
    crouched: t.boolean().default(false),
    sliding: t.boolean().default(false),
    slideRemaining: t.float32().default(0),
    slideCooldown: t.float32().default(0),
    jumpBuffer: t.float32().default(0),
    coyoteRemaining: t.float32().default(0),
    jumpWasDown: t.boolean().default(false),
    crouchWasDown: t.boolean().default(false),
    landed: t.boolean().default(false),
    connected: t.boolean().default(false),
    health: t.float32().default(0),
    maxHealth: t.float32().default(0),
    slot: t.string<'primary' | 'secondary'>().default('primary'),
    secondaryAmmo: t.uint8().default(12),
    landingRemaining: t.float32().default(0),
    aimProgress: t.float32().default(0),
    ammo: t.uint8().default(0),
    reloadRemaining: t.float32().default(0),
    fireRemaining: t.float32().default(0),
    respawnRemaining: t.float32().default(0),
    protectionRemaining: t.float32().default(0),
    kills: t.uint32().default(0),
    deaths: t.uint32().default(0),
    lifeId: t.uint32().default(0),
    ready: t.boolean().default(false),
    weapon: t.string<WeaponId>().default('rifle'),
    lastProcessedInput: t.uint32().default(0),
  },
  'PlayerState',
);
export type PlayerState = SchemaType<typeof PlayerState>;

export const WaveState = schema(
  {
    number: t.uint16().default(0),
    status: t.string<GameSnapshot['wave']['status']>().default('idle'),
    remaining: t.float32().default(0),
    alive: t.uint8().default(0),
    queued: t.uint16().default(0),
    total: t.uint16().default(0),
    cleared: t.uint16().default(0),
    runId: t.uint32().default(0),
  },
  'WaveState',
);
export const ArenaState = schema(
  {
    wave: t.ref(WaveState),
    mapId: t.string().default('switchyard'),
    mode: t.string<GameSnapshot['mode']>().default('arena'),
    hostId: t.string().default(''),
    allyCount: t.uint8().default(0),
    botCount: t.uint8().default(3),
    difficulty: t.string<GameSnapshot['difficulty']>().default('normal'),
    tick: t.uint32().default(0),
    phase: t.string<GameSnapshot['phase']>().default('waiting'),
    round: t.uint32().default(0),
    remaining: t.float32().default(0),
    winner: t.string().default(''),
    players: t.map(PlayerState),
  },
  'ArenaState',
);
export type ArenaState = SchemaType<typeof ArenaState>;

export function toSnapshot(state: ArenaState): GameSnapshot {
  const players: PlayerSnapshot[] = [];
  state.players.forEach((player) =>
    players.push({
      id: player.id,
      bot: player.bot,
      supplyCooldown: player.supplyCooldown,
      bloom: player.bloom,
      secondaryReserve: player.secondaryReserve,
      reserveAmmo: player.reserveAmmo,
      ally: player.ally,
      challenge: {
        kind: player.challenge.kind,
        status: player.challenge.status,
        weapon: player.challenge.weapon,
        runId: player.challenge.runId,
        elapsed: player.challenge.elapsed,
        remaining: player.challenge.remaining,
        duration: player.challenge.duration,
        shots: player.challenge.shots,
        hits: player.challenge.hits,
        headshots: player.challenge.headshots,
        reactionMs: player.challenge.reactionMs,
        checkpoint: player.challenge.checkpoint,
        targetIndex: player.challenge.targetIndex,
        targetTick: player.challenge.targetTick,
      },
      nickname: player.nickname,
      position: { x: player.x, y: player.y, z: player.z },
      velocity: { x: player.vx, y: player.vy, z: player.vz },
      yaw: player.yaw,
      pitch: player.pitch,
      grounded: player.grounded,
      crouched: player.crouched,
      sliding: player.sliding,
      slideRemaining: player.slideRemaining,
      slideCooldown: player.slideCooldown,
      jumpBuffer: player.jumpBuffer,
      coyoteRemaining: player.coyoteRemaining,
      jumpWasDown: player.jumpWasDown,
      crouchWasDown: player.crouchWasDown,
      landed: player.landed,
      connected: player.connected,
      health: player.health,
      maxHealth: player.maxHealth,
      ammo: player.ammo,
      secondaryAmmo: player.secondaryAmmo,
      slot: player.slot,
      aimProgress: player.aimProgress,
      landingRemaining: player.landingRemaining,
      reloadRemaining: player.reloadRemaining,
      fireRemaining: player.fireRemaining,
      respawnRemaining: player.respawnRemaining,
      protectionRemaining: player.protectionRemaining,
      kills: player.kills,
      deaths: player.deaths,
      lifeId: player.lifeId,
      ready: player.ready,
      weapon: player.weapon,
      lastProcessedInput: player.lastProcessedInput,
    }),
  );
  return {
    wave: {
      number: state.wave.number,
      status: state.wave.status,
      remaining: state.wave.remaining,
      alive: state.wave.alive,
      queued: state.wave.queued,
      total: state.wave.total,
      cleared: state.wave.cleared,
      runId: state.wave.runId,
    },
    tick: state.tick,
    mapId: state.mapId,
    mode: state.mode,
    hostId: state.hostId,
    botCount: state.botCount,
    allyCount: state.allyCount,
    difficulty: state.difficulty,
    phase: state.phase,
    round: state.round,
    remaining: state.remaining,
    winner: state.winner,
    players,
  };
}
