import { schema, t } from '@colyseus/schema';
import type { SchemaType } from '@colyseus/schema';
import type {
  GameSnapshot,
  PlayerSnapshot,
  WeaponId,
  ChallengeSnapshot,
  MissionStage,
} from './index.js';

export const ChallengeState = schema(
  {
    kind: t.string<ChallengeSnapshot['kind']>().default('training'),
    status: t.string<ChallengeSnapshot['status']>().default('idle'),
    weapon: t.string<WeaponId>().default('rifle'),
    runId: t.uint32().default(0),
    elapsed: t.float32().default(0),
    remaining: t.float32().default(0),
    duration: t.float32().default(0),
    shots: t.uint32().default(0),
    hits: t.uint32().default(0),
    headshots: t.uint32().default(0),
    reactionMs: t.float32().default(0),
    checkpoint: t.uint8().default(0),
    targetIndex: t.int8().default(-1),
    targetTick: t.uint32().default(0),
  },
  'ChallengeState',
);

export const PlayerState = schema(
  {
    colorIndex: t.uint8().default(0),
    id: t.string().default(''),
    bot: t.boolean().default(false),
    ally: t.boolean().default(false),
    reserveAmmo: t.uint16().default(0),
    secondaryReserve: t.uint16().default(0),
    bloom: t.float32().default(0),
    supplyCooldown: t.float32().default(0),
    mineCooldown: t.float32().default(0),
    grenades: t.uint8().default(1),
    healthCooldown: t.float32().default(0),
    challenge: t.ref(ChallengeState),
    nickname: t.string().default(''),
    x: t.float32().default(0),
    y: t.float32().default(0),
    z: t.float32().default(0),
    vx: t.float32().default(0),
    vy: t.float32().default(0),
    vz: t.float32().default(0),
    yaw: t.float32().default(0),
    pitch: t.float32().default(0),
    grounded: t.boolean().default(false),
    crouched: t.boolean().default(false),
    sliding: t.boolean().default(false),
    slideRemaining: t.float32().default(0),
    slideCooldown: t.float32().default(0),
    jumpBuffer: t.float32().default(0),
    coyoteRemaining: t.float32().default(0),
    jumpWasDown: t.boolean().default(false),
    crouchWasDown: t.boolean().default(false),
    landed: t.boolean().default(false),
    connected: t.boolean().default(false),
    health: t.float32().default(0),
    maxHealth: t.float32().default(0),
    slot: t.string<'primary' | 'secondary' | 'knife'>().default('primary'),
    secondaryAmmo: t.uint8().default(12),
    landingRemaining: t.float32().default(0),
    aimProgress: t.float32().default(0),
    ammo: t.uint8().default(0),
    reloadRemaining: t.float32().default(0),
    fireRemaining: t.float32().default(0),
    respawnRemaining: t.float32().default(0),
    protectionRemaining: t.float32().default(0),
    kills: t.uint32().default(0),
    deaths: t.uint32().default(0),
    lifeId: t.uint32().default(0),
    ready: t.boolean().default(false),
    weapon: t.string<WeaponId>().default('rifle'),
    lastProcessedInput: t.uint32().default(0),
  },
  'PlayerState',
);
export type PlayerState = SchemaType<typeof PlayerState>;

export const WaveState = schema(
  {
    number: t.uint16().default(0),
    status: t.string<GameSnapshot['wave']['status']>().default('idle'),
    remaining: t.float32().default(0),
    alive: t.uint8().default(0),
    queued: t.uint16().default(0),
    total: t.uint16().default(0),
    cleared: t.uint16().default(0),
    runId: t.uint32().default(0),
  },
  'WaveState',
);
export const MineState = schema(
  {
    id: t.string().default(''),
    ownerId: t.string().default(''),
    x: t.float32().default(0),
    y: t.float32().default(0),
    z: t.float32().default(0),
    armed: t.boolean().default(false),
  },
  'MineState',
);
export const GrenadeState = schema(
  {
    id: t.string().default(''),
    ownerId: t.string().default(''),
    x: t.float32().default(0),
    y: t.float32().default(0),
    z: t.float32().default(0),
    remaining: t.float32().default(0),
  },
  'GrenadeState',
);
export const ControlState = schema(
  {
    progress: t.float32().default(0),
    owner: t.string<'neutral' | 'allies' | 'enemies'>().default('neutral'),
    contested: t.boolean().default(false),
    allies: t.uint8().default(0),
    enemies: t.uint8().default(0),
    allyScore: t.float32().default(0),
    enemyScore: t.float32().default(0),
  },
  'ControlState',
);
export const SquadOrderState = schema(
  {
    kind: t.string<'auto' | 'follow' | 'hold' | 'attack'>().default('auto'),
    commanderId: t.string().default(''),
    x: t.float32().default(0),
    y: t.float32().default(0),
    z: t.float32().default(0),
    remaining: t.float32().default(0),
    serial: t.uint32().default(0),
  },
  'SquadOrderState',
);
export const MissionState = schema(
  {
    stage: t.string<MissionStage>().default('idle'),
    checkpoint: t.string<MissionStage>().default('dispatch'),
    progress: t.float32().default(0),
    remaining: t.float32().default(0),
    elapsed: t.float32().default(0),
    carrierId: t.string().default(''),
    cargoX: t.float32().default(0),
    cargoY: t.float32().default(0),
    cargoZ: t.float32().default(0),
    queued: t.uint16().default(0),
    alive: t.uint8().default(0),
    runId: t.uint32().default(0),
    serial: t.uint32().default(0),
    attempts: t.uint16().default(0),
    boarded: t.uint8().default(0),
    required: t.uint8().default(0),
  },
  'MissionState',
);
export const ArenaState = schema(
  {
    wave: t.ref(WaveState),
    mission: t.ref(MissionState),
    control: t.ref(ControlState),
    squadOrder: t.ref(SquadOrderState),
    mapId: t.string().default('switchyard'),
    mode: t.string<GameSnapshot['mode']>().default('arena'),
    hostId: t.string().default(''),
    allyCount: t.uint8().default(0),
    botCount: t.uint8().default(3),
    difficulty: t.string<GameSnapshot['difficulty']>().default('normal'),
    tick: t.uint32().default(0),
    phase: t.string<GameSnapshot['phase']>().default('waiting'),
    round: t.uint32().default(0),
    remaining: t.float32().default(0),
    winner: t.string().default(''),
    players: t.map(PlayerState),
    mines: t.map(MineState),
    grenades: t.map(GrenadeState),
  },
  'ArenaState',
);
export type ArenaState = SchemaType<typeof ArenaState>;

export function toSnapshot(state: ArenaState): GameSnapshot {
  const players: PlayerSnapshot[] = [];
  state.players.forEach((player) =>
    players.push({
      colorIndex: player.colorIndex,
      id: player.id,
      bot: player.bot,
      supplyCooldown: player.supplyCooldown,
      mineCooldown: player.mineCooldown,
      grenades: player.grenades,
      healthCooldown: player.healthCooldown,
      bloom: player.bloom,
      secondaryReserve: player.secondaryReserve,
      reserveAmmo: player.reserveAmmo,
      ally: player.ally,
      challenge: {
        kind: player.challenge.kind,
        status: player.challenge.status,
        weapon: player.challenge.weapon,
        runId: player.challenge.runId,
        elapsed: player.challenge.elapsed,
        remaining: player.challenge.remaining,
        duration: player.challenge.duration,
        shots: player.challenge.shots,
        hits: player.challenge.hits,
        headshots: player.challenge.headshots,
        reactionMs: player.challenge.reactionMs,
        checkpoint: player.challenge.checkpoint,
        targetIndex: player.challenge.targetIndex,
        targetTick: player.challenge.targetTick,
      },
      nickname: player.nickname,
      position: { x: player.x, y: player.y, z: player.z },
      velocity: { x: player.vx, y: player.vy, z: player.vz },
      yaw: player.yaw,
      pitch: player.pitch,
      grounded: player.grounded,
      crouched: player.crouched,
      sliding: player.sliding,
      slideRemaining: player.slideRemaining,
      slideCooldown: player.slideCooldown,
      jumpBuffer: player.jumpBuffer,
      coyoteRemaining: player.coyoteRemaining,
      jumpWasDown: player.jumpWasDown,
      crouchWasDown: player.crouchWasDown,
      landed: player.landed,
      connected: player.connected,
      health: player.health,
      maxHealth: player.maxHealth,
      ammo: player.ammo,
      secondaryAmmo: player.secondaryAmmo,
      slot: player.slot,
      aimProgress: player.aimProgress,
      landingRemaining: player.landingRemaining,
      reloadRemaining: player.reloadRemaining,
      fireRemaining: player.fireRemaining,
      respawnRemaining: player.respawnRemaining,
      protectionRemaining: player.protectionRemaining,
      kills: player.kills,
      deaths: player.deaths,
      lifeId: player.lifeId,
      ready: player.ready,
      weapon: player.weapon,
      lastProcessedInput: player.lastProcessedInput,
    }),
  );
  return {
    control: {
      progress: state.control.progress,
      owner: state.control.owner,
      contested: state.control.contested,
      allies: state.control.allies,
      enemies: state.control.enemies,
      allyScore: state.control.allyScore,
      enemyScore: state.control.enemyScore,
    },
    mission: {
      stage: state.mission.stage,
      checkpoint: state.mission.checkpoint,
      progress: state.mission.progress,
      remaining: state.mission.remaining,
      elapsed: state.mission.elapsed,
      carrierId: state.mission.carrierId,
      cargo: {
        x: state.mission.cargoX,
        y: state.mission.cargoY,
        z: state.mission.cargoZ,
      },
      queued: state.mission.queued,
      alive: state.mission.alive,
      runId: state.mission.runId,
      serial: state.mission.serial,
      attempts: state.mission.attempts,
      boarded: state.mission.boarded,
      required: state.mission.required,
    },
    squadOrder: {
      kind: state.squadOrder.kind,
      commanderId: state.squadOrder.commanderId,
      position: {
        x: state.squadOrder.x,
        y: state.squadOrder.y,
        z: state.squadOrder.z,
      },
      remaining: state.squadOrder.remaining,
      serial: state.squadOrder.serial,
    },
    grenades: [...state.grenades.values()].map((g) => ({
      id: g.id,
      ownerId: g.ownerId,
      position: { x: g.x, y: g.y, z: g.z },
      remaining: g.remaining,
    })),
    mines: [...state.mines.values()].map((mine) => ({
      id: mine.id,
      ownerId: mine.ownerId,
      armed: mine.armed,
      position: { x: mine.x, y: mine.y, z: mine.z },
    })),
    wave: {
      number: state.wave.number,
      status: state.wave.status,
      remaining: state.wave.remaining,
      alive: state.wave.alive,
      queued: state.wave.queued,
      total: state.wave.total,
      cleared: state.wave.cleared,
      runId: state.wave.runId,
    },
    tick: state.tick,
    mapId: state.mapId,
    mode: state.mode,
    hostId: state.hostId,
    botCount: state.botCount,
    allyCount: state.allyCount,
    difficulty: state.difficulty,
    phase: state.phase,
    round: state.round,
    remaining: state.remaining,
    winner: state.winner,
    players,
  };
}
