#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE="$PWD/.env"
[[ -t 0 ]] || { echo "Запусти мастер в интерактивном SSH-терминале."; exit 1; }
[[ "$(uname -s)" == Linux ]] || { echo "Этот мастер запускается только на VM Linux."; exit 1; }
[[ "$(id -u)" != 0 ]] || { echo "Запусти мастер без sudo."; exit 1; }
sudo /usr/bin/docker --host unix:///var/run/docker.sock info >/dev/null
sudo /usr/bin/docker compose version
id github-deploy >/dev/null
sudo test -s /home/github-deploy/.ssh/authorized_keys
if ! sudo grep -Fq 'command="/usr/local/bin/krunker-deploy"' /home/github-deploy/.ssh/authorized_keys; then
  echo "Сначала настрой SSH-ключ с forced command /usr/local/bin/krunker-deploy."
  exit 1
fi

banner "Krunker: автоматический Docker-деплой"

stage "GitHub и план переключения"
say "План: переменные GitHub → конфигурация и ограниченный sudo на VM → доступ к GHCR → включение."
say "SSH-ключи остаются прежними. github-deploy не получит доступ ко всему Docker."
open_url "https://github.com/KrotovPetr/krunker/settings/variables/actions"
step "В Repository variables поставь DEPLOY_ENABLED=false и DEPLOY_MODE=docker."
step "Эти файлы должны быть отправлены в main. На первом push начнутся проверки и публикация образов."
warn "Мастер заменит установленный /usr/local/bin/krunker-deploy. Старые файлы сохранятся в резервной копии."
warn "После переключения управляй игрой через /etc/krunker, а не compose.yaml из клона."
confirm "Деплой выключен и можно подготовить переключение?" || exit 0

stage "Конфигурация и скрипты на VM"
if ! sudo test -f /etc/krunker/deploy.env; then
  say "Для HTTP по IP введи :80. Для HTTPS введи домен без схемы и пути."
  ask SITE_ADDRESS "Адрес сайта:"
  SITE_ADDRESS="${SITE_ADDRESS:-:80}"
  if [[ "$SITE_ADDRESS" != :80 && ! "$SITE_ADDRESS" =~ ^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$ ]]; then
    warn "Нужен домен без схемы и пути либо :80."
    exit 1
  fi
  ask HTTP_PORT "Внешний HTTP-порт, Enter = 80:"
  HTTP_PORT="${HTTP_PORT:-80}"
  ask HTTPS_PORT "Внешний HTTPS-порт, Enter = 443:"
  HTTPS_PORT="${HTTPS_PORT:-443}"
  for port in "$HTTP_PORT" "$HTTPS_PORT"; do
    [[ "$port" =~ ^[1-9][0-9]{0,4}$ ]] && (( 10#$port <= 65535 )) || { warn "Некорректный порт"; exit 1; }
  done
  [[ "$HTTP_PORT" != "$HTTPS_PORT" ]] || { warn "Порты должны отличаться"; exit 1; }
  say "Образы: ghcr.io/krotovpetr/krunker-server и ghcr.io/krotovpetr/krunker-web."
  confirm "Сохранить адрес и порты в /etc/krunker/deploy.env?" || exit 0
  ENV_FILE=$(mktemp)
  write_env KRUNKER_IMAGE_PREFIX ghcr.io/krotovpetr/krunker
  write_env SITE_ADDRESS "$SITE_ADDRESS"
  write_env HTTP_PORT "$HTTP_PORT"
  write_env HTTPS_PORT "$HTTPS_PORT"
  sudo install -d -m 755 -o root -g root /etc/krunker
  sudo install -m 600 -o root -g root "$ENV_FILE" /etc/krunker/deploy.env
  ENV_FILE=/etc/krunker/deploy.env
else
  say "Существующий /etc/krunker/deploy.env сохранится без изменений."
fi
confirm "Установить root-owned Compose, скрипты и ограниченное правило sudo?" || exit 0
FPS_BACKUP_DIR="/etc/krunker/backups/$(date +%Y%m%d%H%M%S)"
sudo install -d -m 700 -o root -g root "$FPS_BACKUP_DIR"
for file in /usr/local/bin/krunker-deploy /usr/local/sbin/krunker-docker-deploy /etc/krunker/compose.yaml /etc/sudoers.d/krunker-docker; do
  if sudo test -f "$file"; then
    sudo cp -a "$file" "$FPS_BACKUP_DIR/$(basename "$file")"
  fi
done
sudo install -m 644 -o root -g root deploy/compose.production.yaml /etc/krunker/compose.yaml
sudo install -m 755 -o root -g root scripts/deploy-docker.sh /usr/local/sbin/krunker-docker-deploy
sudo install -m 755 -o root -g root scripts/deploy-docker-ssh.sh /usr/local/bin/krunker-deploy
FPS_SUDOERS_TMP=$(mktemp)
printf '%s\n' 'github-deploy ALL=(root) NOPASSWD: /usr/local/sbin/krunker-docker-deploy *' > "$FPS_SUDOERS_TMP"
sudo visudo -cf "$FPS_SUDOERS_TMP"
sudo install -m 440 -o root -g root "$FPS_SUDOERS_TMP" /etc/sudoers.d/krunker-docker
sudo env KRUNKER_IMAGE_TAG=0000000000000000000000000000000000000000 \
  /usr/bin/docker compose --project-name krunker --project-directory /etc/krunker \
  --env-file /etc/krunker/deploy.env -f /etc/krunker/compose.yaml config --quiet
say "Предыдущие установленные файлы: $FPS_BACKUP_DIR"
pause "Конфигурация установлена. Enter для доступа к образам."

stage "Чтение Docker-образов"
say "GHCR по умолчанию создаёт приватные пакеты. Для них VM нужен токен только с read:packages."
say "Токен не попадёт в репозиторий или GitHub Secrets. Docker сохранит его в /root/.docker/config.json."
if confirm "Настроить или обновить вход VM в GHCR?"; then
  open_url "https://github.com/settings/tokens"
  step "Создай personal access token classic с read:packages. Для организации при необходимости разреши SSO."
  ENV_FILE=/dev/null
  ask GHCR_USER "GitHub-логин владельца токена:"
  [[ "$GHCR_USER" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]*$ ]] || { warn "Некорректный логин"; exit 1; }
  ask_secret GHCR_READ_TOKEN "Вставь токен, ввод скрыт:"
  test -n "$GHCR_READ_TOKEN"
  sudo install -d -m 700 -o root -g root /root/.docker
  printf '%s' "$GHCR_READ_TOKEN" | sudo /usr/bin/docker --config /root/.docker login ghcr.io -u "$GHCR_USER" --password-stdin
  unset GHCR_READ_TOKEN
  sudo chmod 600 /root/.docker/config.json
else
  say "Продолжай только если образы публичные или вход root в ghcr.io уже настроен."
  confirm "VM сможет скачивать оба образа?" || exit 0
fi
ENV_FILE=/etc/krunker/deploy.env

stage "Включение"
open_url "https://github.com/KrotovPetr/krunker/settings/secrets/actions"
step "Проверь DEPLOY_HOST, DEPLOY_SSH_KEY и DEPLOY_KNOWN_HOSTS. Уже созданные ключи не меняй."
step "Проверь доступ GitHub runner к SSH-порту VM. Домашнего IP в allowlist недостаточно."
step "TCP 80/443 должны быть свободны либо уже заняты этим же Compose-проектом krunker."
warn "При первом Docker-деплое ещё нет записанной предыдущей версии для отката."
confirm "Готов включить обновления? Текущие комнаты будут завершаться при замене сервера." || exit 0
open_url "https://github.com/KrotovPetr/krunker/settings/variables/actions"
step "Поставь DEPLOY_MODE=docker и DEPLOY_ENABLED=true."
open_url "https://github.com/KrotovPetr/krunker/actions"
step "Отправь новый коммит в main либо выбери Re-run all jobs у запуска Checks от push текущего main."
pause "Нажми Enter после настройки переменных GitHub."
finish
say "Настройка подготовлена. Первый деплой ещё нужно подтвердить по Actions и проверкой комнаты."
say "На VM не нужен git pull для последующих обновлений игры."
