#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Run from the checkout, never relative to the caller's working directory.
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE="$PWD/.env"
[[ -t 0 ]] || { echo "Запусти мастер в интерактивном SSH-терминале."; exit 1; }
[[ -r /etc/os-release ]] || { echo "Этот мастер предназначен для Ubuntu VM."; exit 1; }
. /etc/os-release
[[ "$ID" == ubuntu ]] || { echo "Этот мастер предназначен для Ubuntu VM."; exit 1; }
[[ "$(id -u)" != 0 ]] || { echo "Запусти bash scripts/setup-docker.sh без sudo."; exit 1; }

banner "Krunker: Docker на VM"

stage "Подготовка"
say "План: Docker и Compose → адрес сайта в .env → сборка → запуск и проверка."
say "Ключи SSH, authorized_keys и существующие службы мастер не меняет."
open_url "https://github.com/KrotovPetr/krunker/settings/variables/actions"
step "Если включён старый автодеплой, поставь DEPLOY_ENABLED=false."
step "В группе безопасности VM разреши TCP 80 и 443. Порт 2567 не открывай."
warn "Docker публикует порты в обход правил UFW; проверь облачную группу безопасности."
confirm "Продолжить настройку на этой VM?" || exit 0

stage "Docker и Compose"
if ! command -v docker >/dev/null 2>&1; then
  open_url "https://docs.docker.com/engine/install/ubuntu/#install-using-the-apt-repository"
  say "Установлю Docker Engine и Compose из официального apt-репозитория."
  confirm "Установить пакеты через sudo?" || exit 0
  # Do not replace an existing installation or its apt repository silently.
  if [[ -e /etc/apt/sources.list.d/docker.sources || -e /etc/apt/sources.list.d/docker.list ]]; then
    warn "Репозиторий Docker уже настроен. Заверши установку по документации и повтори запуск."
    exit 1
  fi
  sudo apt-get update
  sudo apt-get install -y ca-certificates curl
  sudo install -m 0755 -d /etc/apt/keyrings
  FPS_DOCKER_TMP=$(mktemp -d)
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o "$FPS_DOCKER_TMP/docker.asc"
  sudo install -m 0644 "$FPS_DOCKER_TMP/docker.asc" /etc/apt/keyrings/docker.asc
  sudo tee /etc/apt/sources.list.d/docker.sources >/dev/null <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: ${UBUNTU_CODENAME:-$VERSION_CODENAME}
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF
  sudo apt-get update
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo systemctl enable --now docker
fi
sudo docker info >/dev/null
sudo docker compose version
pause "Docker доступен. Enter для настройки адреса."

stage "Адрес и сборка"
say "Для запуска по IP оставь поле пустым: HTTP на порту 80."
say "Для HTTPS введи домен без https://, например play.example.com."
say "Домен должен указывать на эту VM; TCP 80 и 443 должны быть доступны."
ask SITE_ADDRESS "Адрес сайта:"
SITE_ADDRESS="${SITE_ADDRESS:-:80}"
if [[ "$SITE_ADDRESS" != :80 && ! "$SITE_ADDRESS" =~ ^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$ ]]; then
  warn "Нужен домен без схемы, пути и порта либо :80."
  exit 1
fi
confirm "Сохранить SITE_ADDRESS=$SITE_ADDRESS в .env?" || exit 0
write_env SITE_ADDRESS "$SITE_ADDRESS"
sudo docker compose config --quiet
say "Сначала соберу оба образа. Работающие контейнеры пока не останавливаются."
confirm "Начать сборку? Первый запуск может занять несколько минут." || exit 0
sudo docker compose build

stage "Запуск"
warn "Обновление контейнеров завершает текущие игровые комнаты."
say "Если порт 80/443 занят старым Caddy или другим сайтом, сначала разберись с этим сервисом."
say "Мастер не останавливает чужие службы и не удаляет контейнеры или данные."
confirm "Запустить контейнеры на портах из compose.yaml/.env?" || exit 0
sudo docker compose up -d --wait --wait-timeout 120
sudo docker compose ps
sudo docker compose exec -T web wget -q -O - http://127.0.0.1:8080/health
printf '\n'
if [[ "$SITE_ADDRESS" == :80 ]]; then
  say "Открой http://ПУБЛИЧНЫЙ_IP_VM в браузере."
else
  open_url "https://$SITE_ADDRESS"
fi
step "Создай комнату и зайди вторым игроком. Проверь движение и стрельбу."
if ! confirm "Сайт и комната работают?"; then
  sudo docker compose logs --tail=80
  warn "Контейнеры оставлены для диагностики. Первый запуск ещё не подтверждён."
  exit 1
fi

finish
say "Обновление: git pull --ff-only && sudo docker compose build && sudo docker compose up -d --wait"
say "Старый DEPLOY_ENABLED оставь false: он запускает деплой через systemd."

